const express = require('express')
const routes = express.Router()
const multerConfig = require('./config/multer')
const upload = require('multer')(multerConfig)
const UserController = require('./app/controllers/UserController')
const SessionController = require('./app/controllers/SessionController')
const DashboardController = require('./app/controllers/DashboardController')
const FileController = require('./app/controllers/FileController')
const AvailableController = require('./app/controllers/AvailableController')
const AppointmentController = require('./app/controllers/AppointmentController')
const AuthMiddleware = require('./app/middlewares/auth')
const GuestMiddleware = require('./app/middlewares/guest')

routes.use((req, res, next) => {
  res.locals.flashSuccess = req.flash('success')
  res.locals.flashError = req.flash('error')
  res.locals.flashInfo = req.flash('info')
  return next()
})

routes.get('/files/:file', FileController.show)
routes.get('/', GuestMiddleware, SessionController.create)
routes.post('/signin', SessionController.store)
routes.get('/signup', GuestMiddleware, UserController.create)
routes.post('/signup', upload.single('avatar'), UserController.store)

routes.use('/app', AuthMiddleware)
routes.get('/app/dashboard', DashboardController.index)
routes.get('/app/logout', SessionController.destroy)
routes.get('/app/appointments/new/:provider', AppointmentController.create)
routes.get('/app/available/:provider', AvailableController.index)
module.exports = routes
